import json
import sqlite3
from datetime import datetime, timedelta
import io
import socket
from urllib.parse import parse_qs, quote_plus, urlparse

import qrcode
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer

from flask import Blueprint, current_app, flash, jsonify, redirect, render_template, request, send_file, session, url_for

from .db import get_db
from .face import decode_data_url, extract_face_encoding, is_face_available, match_face
from .unique_id import normalize_unique_id
from .security import login_required, role_required
from .utils import date_iso, from_json, now_iso, to_json

attendance_bp = Blueprint("attendance", __name__, url_prefix="/attendance")

DEFAULT_SUBJECTS = ["DBMS", "PPS", "Python", "Web Analytics", "Cloud Computing"]
REQUIRED_METHODS = ("unique_id", "face", "qr")
QR_TOKEN_TTL_SECONDS = 120
WEEKDAY_OPTIONS = [
    (0, "Monday"),
    (1, "Tuesday"),
    (2, "Wednesday"),
    (3, "Thursday"),
    (4, "Friday"),
    (5, "Saturday"),
    (6, "Sunday"),
]


def _normalize_subject(raw_subject):
    subject = (raw_subject or "General").strip()
    return subject[:60] if subject else "General"


def _parse_qr_payload(raw_qr, fallback_subject):
    qr_data = (raw_qr or "").strip()
    if not qr_data:
        return None, None

    subject = _normalize_subject(fallback_subject)

    try:
        data = json.loads(qr_data)
        code = (data.get("student_code") or data.get("unique_id") or "").strip()
        subject = _normalize_subject(data.get("subject") or subject)
        return code, subject
    except Exception:
        pass

    if "|" in qr_data:
        left, right = qr_data.split("|", 1)
        return left.strip(), _normalize_subject(right)

    if ":" in qr_data:
        left, right = qr_data.split(":", 1)
        return left.strip(), _normalize_subject(right)

    return qr_data, subject


def _qr_serializer():
    return URLSafeTimedSerializer(current_app.config["SECRET_KEY"])


def _build_session_qr_token(subject):
    subject = _normalize_subject(subject)
    data = {"kind": "session", "subject": subject}
    return _qr_serializer().dumps(data, salt="attendance-qr")


def _make_scanner_qr_value(token):
    configured_base = (current_app.config.get("PUBLIC_BASE_URL") or "").strip().rstrip("/")
    if configured_base:
        base = configured_base
    else:
        parsed = urlparse(request.host_url)
        host = (parsed.hostname or "").lower()
        port = parsed.port
        scheme = parsed.scheme or "http"

        if host in ("127.0.0.1", "localhost"):
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                sock.connect(("8.8.8.8", 80))
                lan_ip = sock.getsockname()[0]
                sock.close()
                if lan_ip and lan_ip not in ("127.0.0.1", "0.0.0.0"):
                    base = f"{scheme}://{lan_ip}:{port}" if port else f"{scheme}://{lan_ip}"
                else:
                    base = request.host_url.rstrip("/")
            except Exception:
                try:
                    lan_ip = socket.gethostbyname(socket.gethostname())
                    if lan_ip and lan_ip not in ("127.0.0.1", "0.0.0.0"):
                        base = f"{scheme}://{lan_ip}:{port}" if port else f"{scheme}://{lan_ip}"
                    else:
                        base = request.host_url.rstrip("/")
                except Exception:
                    base = request.host_url.rstrip("/")
        else:
            base = request.host_url.rstrip("/")

    path = url_for("attendance.qr_scan")
    return f"{base}{path}?t={quote_plus(token)}"


def _extract_qr_token_candidate(raw_qr):
    qr_data = (raw_qr or "").strip()
    if not qr_data:
        return ""

    if qr_data.startswith("SAQR|"):
        return qr_data.split("|", 1)[1].strip()

    parsed = urlparse(qr_data)
    if parsed.scheme in ("http", "https") and parsed.query:
        query = parse_qs(parsed.query)
        for key in ("t", "token", "qr", "qr_token"):
            values = query.get(key)
            if values and values[0].strip():
                return values[0].strip()

    return qr_data


def _read_qr_token_with_reason(token, max_age_seconds=QR_TOKEN_TTL_SECONDS):
    if not token:
        return None, "QR token missing"
    try:
        data = _qr_serializer().loads(token, salt="attendance-qr", max_age=max_age_seconds)
        if isinstance(data, dict):
            # New session token generated by teacher/admin.
            if data.get("kind") == "session" and data.get("subject"):
                return _normalize_subject(data.get("subject", "General")), None
            # Backward compatibility for old student-bound tokens.
            if data.get("student_id") and data.get("subject"):
                return _normalize_subject(data.get("subject", "General")), None
        return None, "Invalid QR payload"
    except SignatureExpired:
        return None, "QR expired. Generate a new QR and scan again."
    except (BadSignature, ValueError, TypeError):
        return None, "Invalid QR token"


def _read_student_qr_token(token, max_age_seconds=QR_TOKEN_TTL_SECONDS):
    try:
        data = _qr_serializer().loads(token, salt="attendance-qr", max_age=max_age_seconds)
        if isinstance(data, dict):
            if data.get("student_id"):
                return int(data["student_id"]), _normalize_subject(data.get("subject", "General"))
            if data.get("kind") == "session" and data.get("subject"):
                return None, _normalize_subject(data.get("subject", "General"))
    except (BadSignature, SignatureExpired, ValueError, TypeError):
        return None, None
    return None, None


def _current_student_id():
    student_id = session.get("student_id")
    if student_id:
        return int(student_id)
    if session.get("role") != "student":
        return None

    db = get_db()
    row = db.execute("SELECT student_id FROM users WHERE id = ?", (session.get("user_id"),)).fetchone()
    if not row or not row["student_id"]:
        return None
    session["student_id"] = row["student_id"]
    return int(row["student_id"])


def _get_timetable_for_section(section_name, weekday=None):
    if not section_name:
        return []
    db = get_db()
    if weekday is None:
        weekday = datetime.now().weekday()
    return db.execute(
        """
        SELECT id, section_name, weekday, subject, start_time, end_time
        FROM timetable
        WHERE section_name = ? AND weekday = ?
        ORDER BY start_time
        """,
        (section_name, int(weekday)),
    ).fetchall()


def _get_period_for_student_subject(student_id, subject, weekday=None, current_hhmm=None):
    db = get_db()
    if weekday is None:
        weekday = datetime.now().weekday()
    if current_hhmm is None:
        current_hhmm = datetime.now().strftime("%H:%M")

    active = db.execute(
        """
        SELECT t.id, t.subject, t.start_time, t.end_time, s.section_name
        FROM students s
        JOIN timetable t ON t.section_name = s.section_name
        WHERE s.id = ? AND s.active = 1 AND t.weekday = ? AND t.subject = ?
          AND t.start_time <= ? AND t.end_time >= ?
        ORDER BY t.start_time
        LIMIT 1
        """,
        (student_id, int(weekday), subject, current_hhmm, current_hhmm),
    ).fetchone()
    if active:
        return active

    # Fallback: nearest matching period for the day (upcoming first, then latest ended).
    upcoming = db.execute(
        """
        SELECT t.id, t.subject, t.start_time, t.end_time, s.section_name
        FROM students s
        JOIN timetable t ON t.section_name = s.section_name
        WHERE s.id = ? AND s.active = 1 AND t.weekday = ? AND t.subject = ?
          AND t.end_time >= ?
        ORDER BY t.start_time
        LIMIT 1
        """,
        (student_id, int(weekday), subject, current_hhmm),
    ).fetchone()
    if upcoming:
        return upcoming

    return db.execute(
        """
        SELECT t.id, t.subject, t.start_time, t.end_time, s.section_name
        FROM students s
        JOIN timetable t ON t.section_name = s.section_name
        WHERE s.id = ? AND s.active = 1 AND t.weekday = ? AND t.subject = ?
        ORDER BY t.end_time DESC
        LIMIT 1
        """,
        (student_id, int(weekday), subject),
    ).fetchone()


def _resolve_active_subject_for_mark(student_id, requested_subject, mode):
    """Prefer a recent in-progress row for the same student/method.

    This keeps method-order behavior consistent: whichever method is marked first,
    the next method marks the same active row and only true pending methods remain.
    """
    if mode not in REQUIRED_METHODS:
        return _normalize_subject(requested_subject)

    db = get_db()
    now_dt = datetime.now()
    today = date_iso()
    recent_cutoff_ts = (now_dt - timedelta(minutes=20)).strftime("%Y-%m-%d %H:%M:%S")
    requested_subject = _normalize_subject(requested_subject)

    recent_rows = db.execute(
        """
        SELECT subject, status, mode, note, unique_id_done, face_done, qr_done
        FROM attendance
        WHERE student_id = ?
          AND date = ?
          AND timestamp >= ?
        ORDER BY id DESC
        LIMIT 10
        """,
        (student_id, today, recent_cutoff_ts),
    ).fetchall()

    for row in recent_rows:
        is_manual_baseline = row["mode"] == "manual" and row["status"] in ("absent", "late")
        is_auto_absent_note = str(row["note"] or "").startswith("Auto absent")
        if is_manual_baseline or is_auto_absent_note:
            continue

        flags = {
            "unique_id": int(row["unique_id_done"] or 0),
            "face": int(row["face_done"] or 0),
            "qr": int(row["qr_done"] or 0),
        }

        any_done = any(flags[m] == 1 for m in REQUIRED_METHODS)
        all_done = all(flags[m] == 1 for m in REQUIRED_METHODS)
        current_pending = flags[mode] != 1

        if any_done and not all_done and current_pending and row["subject"]:
            return _normalize_subject(row["subject"])

    return requested_subject


def _apply_auto_absences(now_dt=None):
    db = get_db()
    now_dt = now_dt or datetime.now()
    today = date_iso()
    weekday = now_dt.weekday()
    current_hhmm = now_dt.strftime("%H:%M")
    ts = now_iso()

    due_rows = db.execute(
        """
        SELECT s.id AS student_id, t.subject, t.end_time
        FROM timetable t
        JOIN students s ON s.section_name = t.section_name
        WHERE s.active = 1
          AND t.weekday = ?
          AND t.end_time <= ?
        """,
        (weekday, current_hhmm),
    ).fetchall()

    created_count = 0
    updated_count = 0
    for row in due_rows:
        existing = db.execute(
            "SELECT id, status FROM attendance WHERE student_id = ? AND date = ? AND subject = ?",
            (row["student_id"], today, row["subject"]),
        ).fetchone()

        if existing:
            if existing["status"] != "present":
                note = f"Auto absent: not present before period end {row['end_time']}"
                db.execute(
                    """
                    UPDATE attendance
                    SET status = 'absent', mode = 'manual', unique_id_done = 0, face_done = 0, qr_done = 0, timestamp = ?, synced = 0, note = ?
                    WHERE id = ?
                    """,
                    (ts, note, existing["id"]),
                )
                db.execute(
                    "INSERT INTO sync_queue (entity_type, entity_id, operation, payload) VALUES (?, ?, ?, ?)",
                    (
                        "attendance",
                        existing["id"],
                        "update",
                        to_json(
                            {
                                "attendance_id": existing["id"],
                                "student_id": row["student_id"],
                                "date": today,
                                "subject": row["subject"],
                                "status": "absent",
                                "mode": "manual",
                                "unique_id_done": 0,
                                "face_done": 0,
                                "qr_done": 0,
                                "all_methods_completed": False,
                                "pending_methods": list(REQUIRED_METHODS),
                                "timestamp": ts,
                                "note": note,
                            }
                        ),
                    ),
                )
                updated_count += 1
            continue

        note = f"Auto absent: no present mark before period end {row['end_time']}"
        cursor = db.execute(
            """
            INSERT INTO attendance (student_id, date, subject, status, mode, unique_id_done, face_done, qr_done, timestamp, synced, note)
            VALUES (?, ?, ?, 'absent', 'manual', 0, 0, 0, ?, 0, ?)
            """,
            (row["student_id"], today, row["subject"], ts, note),
        )
        attendance_id = cursor.lastrowid
        db.execute(
            "INSERT INTO sync_queue (entity_type, entity_id, operation, payload) VALUES (?, ?, ?, ?)",
            (
                "attendance",
                attendance_id,
                "insert",
                to_json(
                    {
                        "attendance_id": attendance_id,
                        "student_id": row["student_id"],
                        "date": today,
                        "subject": row["subject"],
                        "status": "absent",
                        "mode": "manual",
                        "unique_id_done": 0,
                        "face_done": 0,
                        "qr_done": 0,
                        "all_methods_completed": False,
                        "pending_methods": list(REQUIRED_METHODS),
                        "timestamp": ts,
                        "note": note,
                    }
                ),
            ),
        )
        created_count += 1

    if created_count or updated_count:
        db.commit()
    return created_count + updated_count


@attendance_bp.route("/timetable", methods=["GET", "POST"])
@login_required
@role_required("admin")
def timetable_page():
    db = get_db()
    if request.method == "POST":
        section_name = request.form.get("section_name", "").strip()
        weekday = request.form.get("weekday", type=int)
        subject = _normalize_subject(request.form.get("subject", "General"))
        start_time = (request.form.get("start_time", "") or "").strip()
        end_time = (request.form.get("end_time", "") or "").strip()

        if not section_name or weekday is None or not start_time or not end_time:
            flash("Section, weekday, subject, start and end time are required", "error")
            return redirect(url_for("attendance.timetable_page"))
        if len(start_time) != 5 or len(end_time) != 5 or start_time >= end_time:
            flash("Enter valid HH:MM times and ensure end time is after start time", "error")
            return redirect(url_for("attendance.timetable_page"))

        try:
            db.execute(
                """
                INSERT INTO timetable (section_name, weekday, subject, start_time, end_time)
                VALUES (?, ?, ?, ?, ?)
                """,
                (section_name, weekday, subject, start_time, end_time),
            )
            db.commit()
            flash("Timetable period added", "success")
        except Exception:
            flash("This section already has the same subject for that weekday", "error")
        return redirect(url_for("attendance.timetable_page"))

    sections = db.execute("SELECT DISTINCT section_name FROM students WHERE active = 1 ORDER BY section_name").fetchall()
    entries = db.execute(
        "SELECT id, section_name, weekday, subject, start_time, end_time FROM timetable ORDER BY section_name, weekday, start_time"
    ).fetchall()
    weekday_map = {idx: name for idx, name in WEEKDAY_OPTIONS}
    return render_template(
        "timetable.html",
        sections=[r["section_name"] for r in sections],
        entries=entries,
        weekday_options=WEEKDAY_OPTIONS,
        weekday_map=weekday_map,
    )


@attendance_bp.route("/timetable/<int:entry_id>/delete", methods=["POST"])
@login_required
@role_required("admin")
def delete_timetable_entry(entry_id):
    db = get_db()
    db.execute("DELETE FROM timetable WHERE id = ?", (entry_id,))
    db.commit()
    flash("Timetable period removed", "success")
    return redirect(url_for("attendance.timetable_page"))


@attendance_bp.route("/dashboard")
@login_required
def dashboard():
    db = get_db()
    today = date_iso()
    _apply_auto_absences()

    if session.get("role") == "student":
        student_id = _current_student_id()
        student = db.execute(
            "SELECT id, student_code, name, section_name, section FROM students WHERE id = ? AND active = 1",
            (student_id,),
        ).fetchone()
        if not student:
            flash("Student account is not linked properly", "error")
            return redirect(url_for("auth.logout"))

        stats_row = db.execute(
            """
            SELECT
                COUNT(id) AS total_classes,
                SUM(CASE WHEN status = 'present' THEN 1 ELSE 0 END) AS present_classes,
                SUM(CASE WHEN status = 'absent' THEN 1 ELSE 0 END) AS absent_classes
            FROM attendance
            WHERE student_id = ?
            """,
            (student_id,),
        ).fetchone()

        total_classes = int(stats_row["total_classes"] or 0)
        present_classes = int(stats_row["present_classes"] or 0)
        absent_classes = int(stats_row["absent_classes"] or 0)
        overall_percent = round((present_classes / total_classes) * 100, 1) if total_classes > 0 else 100.0
        is_defaulter = overall_percent < 75.0 and total_classes > 0

        # Subject breakdown for student
        sub_rows = db.execute(
            """
            SELECT
                subject,
                COUNT(id) AS total,
                SUM(CASE WHEN status = 'present' THEN 1 ELSE 0 END) AS present
            FROM attendance
            WHERE student_id = ?
            GROUP BY subject
            ORDER BY subject
            """,
            (student_id,),
        ).fetchall()

        subject_breakdown = []
        for sr in sub_rows:
            stot = int(sr["total"] or 0)
            spres = int(sr["present"] or 0)
            sperc = round((spres / stot) * 100, 1) if stot > 0 else 0.0
            subject_breakdown.append(
                {
                    "subject": sr["subject"],
                    "total": stot,
                    "present": spres,
                    "absent": stot - spres,
                    "percent": sperc,
                    "is_defaulter": sperc < 75.0 and stot > 0,
                }
            )

        timetable_rows = _get_timetable_for_section(student["section_name"])
        recent_attendance = db.execute(
            "SELECT date, subject, status, mode, timestamp FROM attendance WHERE student_id = ? ORDER BY date DESC, id DESC LIMIT 20",
            (student_id,),
        ).fetchall()

        student_analytics = {
            "total_classes": total_classes,
            "present_classes": present_classes,
            "absent_classes": absent_classes,
            "overall_percent": overall_percent,
            "is_defaulter": is_defaulter,
            "subject_breakdown": subject_breakdown,
        }

        return render_template(
            "dashboard.html",
            today=today,
            timetable_rows=timetable_rows,
            recent_attendance=recent_attendance,
            student_profile=student,
            student_analytics=student_analytics,
        )

    # Admin / Teacher dashboard data
    student_count_row = db.execute("SELECT COUNT(*) AS count FROM students WHERE active = 1").fetchone()
    student_count = int(student_count_row["count"] or 0)

    today_stats = db.execute(
        """
        SELECT
            COUNT(DISTINCT CASE WHEN status = 'present' THEN student_id END) AS today_present,
            COUNT(DISTINCT CASE WHEN status = 'absent' THEN student_id END) AS today_absent,
            COUNT(id) AS total_sessions_today
        FROM attendance
        WHERE date = ?
        """,
        (today,),
    ).fetchone()

    today_present = int(today_stats["today_present"] or 0)
    today_absent = int(today_stats["today_absent"] or 0)
    total_sessions_today = int(today_stats["total_sessions_today"] or 0)
    today_rate = round((today_present / student_count) * 100, 1) if student_count > 0 else 0.0

    # Defaulters count across entire database (< 75%)
    defaulters_row = db.execute(
        """
        SELECT COUNT(*) AS cnt FROM (
            SELECT s.id,
                   COUNT(a.id) AS total,
                   SUM(CASE WHEN a.status = 'present' THEN 1 ELSE 0 END) AS pres
            FROM students s
            JOIN attendance a ON a.student_id = s.id
            WHERE s.active = 1
            GROUP BY s.id
            HAVING total > 0 AND (CAST(pres AS FLOAT) / total) < 0.75
        )
        """
    ).fetchone()
    defaulters_count = int(defaulters_row["cnt"] or 0) if defaulters_row else 0

    # 7-day trend chart data
    today_dt = datetime.now().date()
    start_7d = today_dt - timedelta(days=6)
    date_list = [(start_7d + timedelta(days=i)).strftime("%Y-%m-%d") for i in range(7)]

    trend_rows = db.execute(
        """
        SELECT
            date,
            SUM(CASE WHEN status = 'present' THEN 1 ELSE 0 END) AS pres,
            SUM(CASE WHEN status != 'present' THEN 1 ELSE 0 END) AS abse
        FROM attendance
        WHERE date BETWEEN ? AND ?
        GROUP BY date
        ORDER BY date
        """,
        (str(start_7d), str(today_dt)),
    ).fetchall()

    trend_map = {r["date"]: {"present": int(r["pres"] or 0), "absent": int(r["abse"] or 0)} for r in trend_rows}
    trend_7d_data = {
        "labels": date_list,
        "present": [trend_map.get(d, {}).get("present", 0) for d in date_list],
        "absent": [trend_map.get(d, {}).get("absent", 0) for d in date_list],
    }

    sections = db.execute(
        "SELECT section_name, COUNT(*) as total FROM students WHERE active = 1 GROUP BY section_name ORDER BY section_name"
    ).fetchall()

    totals = {
        "student_count": student_count,
        "today_present": today_present,
        "today_absent": today_absent,
        "today_rate": today_rate,
        "total_sessions_today": total_sessions_today,
        "defaulters_count": defaulters_count,
    }

    return render_template(
        "dashboard.html",
        today=today,
        totals=totals,
        trend_7d_data=trend_7d_data,
        sections=sections,
        recent_attendance=[],
    )


@attendance_bp.route("/mark", methods=["GET"])
@login_required
@role_required("teacher", "student")
def mark_page():
    _apply_auto_absences()
    if session.get("role") == "student":
        student_id = _current_student_id()
        db = get_db()
        student = db.execute(
            "SELECT id, student_code, name, section_name, section FROM students WHERE id = ? AND active = 1",
            (student_id,),
        ).fetchone()
        own_attendance = db.execute(
            "SELECT date, subject, status, mode, timestamp FROM attendance WHERE student_id = ? ORDER BY date DESC, id DESC LIMIT 20",
            (student_id,),
        ).fetchall()
        timetable_rows = _get_timetable_for_section(student["section_name"])
        timetable_subjects = [r["subject"] for r in timetable_rows]
        return render_template(
            "attendance_mark.html",
            ai_enabled=is_face_available(),
            subjects=timetable_subjects or DEFAULT_SUBJECTS,
            student_mode=True,
            student=student,
            own_attendance=own_attendance,
            timetable_rows=timetable_rows,
        )

    return render_template(
        "attendance_mark.html",
        ai_enabled=is_face_available(),
        subjects=DEFAULT_SUBJECTS,
        student_mode=False,
        timetable_rows=[],
    )


@attendance_bp.route("/self-mark", methods=["POST"])
@login_required
@role_required("student")
def self_mark():
    student_id = _current_student_id()
    if not student_id:
        flash("Student account is not linked", "error")
        return redirect(url_for("attendance.mark_page"))
    subject = _normalize_subject(request.form.get("subject", "General"))
    result = mark_attendance(student_id, status="present", mode="manual", subject=subject, note="Self marked")
    if result["all_methods_completed"]:
        flash(f"Attendance marked present for {subject}", "success")
    else:
        pending = ", ".join(result["pending_methods"])
        flash(f"Self mark saved, but not present yet. Pending: {pending}", "warning")
    return redirect(url_for("attendance.mark_page"))


@attendance_bp.route("/api/qr/generate", methods=["POST"])
@login_required
@role_required("teacher", "admin")
def api_generate_session_qr():
    payload = request.get_json(silent=True) or {}
    subject = _normalize_subject(payload.get("subject", "General"))
    token = _build_session_qr_token(subject)
    qr_value = _make_scanner_qr_value(token)
    return jsonify(
        {
            "ok": True,
            "token": token,
            "qr_value": qr_value,
            "subject": subject,
            "expires_in": QR_TOKEN_TTL_SECONDS,
        }
    )


@attendance_bp.route("/qr/session.png")
@login_required
@role_required("teacher", "admin")
def session_qr_png():
    subject = _normalize_subject(request.args.get("subject", "General"))
    token = _build_session_qr_token(subject)
    qr_value = _make_scanner_qr_value(token)

    qr = qrcode.QRCode(version=4, box_size=8, border=2)
    qr.add_data(qr_value)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buffer = io.BytesIO()
    img.save(buffer, format="PNG")
    buffer.seek(0)
    return send_file(buffer, mimetype="image/png")


@attendance_bp.route("/qr/scan", methods=["GET", "POST"])
def qr_scan():
    raw_token = request.values.get("t") or request.values.get("token") or ""
    token = _extract_qr_token_candidate(raw_token)
    subject, err = _read_qr_token_with_reason(token)

    if err or not subject:
        html = f"""
        <html><body style='font-family:Arial,sans-serif;padding:24px;'>
        <h2>QR Scan Failed</h2>
        <p>{err or 'Invalid QR token'}</p>
        </body></html>
        """
        return html, 400

    if request.method == "GET":
        html = f"""
        <html><body style='font-family:Arial,sans-serif;padding:24px;'>
        <h2>Attendance QR Scanned</h2>
        <p>Subject: <strong>{subject}</strong></p>
        <p>Enter your Roll No and submit attendance.</p>
        <form method='post'>
          <input type='hidden' name='t' value='{token}'>
          <input type='text' name='roll_no' placeholder='Roll No' required style='padding:10px 12px;border:1px solid #b7c4bf;border-radius:8px;min-width:220px;margin-right:8px;'>
          <button type='submit' style='padding:10px 16px;border:0;border-radius:8px;background:#0b7d69;color:#fff;cursor:pointer;'>Submit Attendance</button>
        </form>
        </body></html>
        """
        return html

    roll_no = (request.form.get("roll_no") or "").strip()
    if not roll_no:
        return (
            "<html><body style='font-family:Arial,sans-serif;padding:24px;'><h2>QR Scan Failed</h2><p>Roll No is required.</p></body></html>",
            400,
        )

    db = get_db()
    student = db.execute(
        "SELECT id, name FROM students WHERE student_code = ? AND active = 1",
        (roll_no,),
    ).fetchone()
    if not student:
        return (
            "<html><body style='font-family:Arial,sans-serif;padding:24px;'><h2>QR Scan Failed</h2><p>Invalid Roll No</p></body></html>",
            404,
        )

    subject = _resolve_active_subject_for_mark(student["id"], subject, "qr")
    result = mark_attendance(student["id"], status="present", mode="qr", subject=subject)
    heading = "Attendance Marked" if result["newly_completed"] else ("Already Completed" if result["all_methods_completed"] else "QR Recorded")
    if result["newly_completed"]:
        detail = f"<strong>{student['name']}</strong> marked present for <strong>{result['subject']}</strong>."
    elif result["all_methods_completed"]:
        detail = f"Attendance for <strong>{result['subject']}</strong> is already completed today for <strong>{student['name']}</strong>."
    else:
        detail = f"<strong>{student['name']}</strong> QR recorded for <strong>{result['subject']}</strong>. Pending: {', '.join(result['pending_methods'])}."
    html = f"""
    <html><body style='font-family:Arial,sans-serif;padding:24px;'>
    <h2>{heading}</h2>
    <p>{detail}</p>
    <p>Time: {result['time']}</p>
    </body></html>
    """
    return html


@attendance_bp.route("/manual", methods=["POST"])
@login_required
@role_required("teacher")
def manual_mark():
    _apply_auto_absences()
    student_id = request.form.get("student_id", type=int)
    status = request.form.get("status", "present")
    subject = _normalize_subject(request.form.get("subject", "General"))
    note = request.form.get("note", "").strip()

    if not student_id:
        flash("Invalid student", "error")
        return redirect(url_for("attendance.mark_page"))

    # Teacher manual marking should directly apply selected status, including present.
    allow_override = True
    mark_attendance(
        student_id,
        status=status,
        mode="manual",
        note=note,
        subject=subject,
        manual_override=allow_override,
    )
    flash("Attendance updated", "success")
    return redirect(url_for("attendance.mark_page"))


@attendance_bp.route("/api/students")
@login_required
@role_required("teacher")
def api_students():
    section_name = request.args.get("section", "").strip()
    db = get_db()
    if section_name:
        rows = db.execute(
            "SELECT id, student_code, name, section_name, section FROM students WHERE active = 1 AND section_name = ? ORDER BY name",
            (section_name,),
        ).fetchall()
    else:
        rows = db.execute(
            "SELECT id, student_code, name, section_name, section FROM students WHERE active = 1 ORDER BY section_name, name"
        ).fetchall()
    return jsonify([dict(r) for r in rows])


@attendance_bp.route("/api/progress", methods=["GET"])
@login_required
@role_required("student")
def api_progress():
    student_id = _current_student_id()
    if not student_id:
        return jsonify({"ok": False, "message": "Student account is not linked"}), 400

    subject = _normalize_subject(request.args.get("subject", "General"))
    today = date_iso()
    db = get_db()
    row = db.execute(
        """
        SELECT id, subject, status, mode, unique_id_done, face_done, qr_done, timestamp
        FROM attendance
        WHERE student_id = ? AND date = ? AND subject = ?
        ORDER BY id DESC
        LIMIT 1
        """,
        (student_id, today, subject),
    ).fetchone()

    if not row:
        return jsonify(
            {
                "ok": True,
                "found": False,
                "subject": subject,
                "pending_methods": list(REQUIRED_METHODS),
                "all_methods_completed": False,
            }
        )

    flags = {
        "unique_id": int(row["unique_id_done"] or 0),
        "face": int(row["face_done"] or 0),
        "qr": int(row["qr_done"] or 0),
    }
    pending_methods = [m for m in REQUIRED_METHODS if flags[m] != 1]
    all_done = all(flags[m] == 1 for m in REQUIRED_METHODS)

    return jsonify(
        {
            "ok": True,
            "found": True,
            "subject": row["subject"],
            "status": row["status"],
            "mode": row["mode"],
            "time": row["timestamp"],
            "unique_id_done": flags["unique_id"],
            "face_done": flags["face"],
            "qr_done": flags["qr"],
            "pending_methods": pending_methods,
            "all_methods_completed": all_done,
        }
    )


@attendance_bp.route("/api/mark/unique-id", methods=["POST"])
@login_required
@role_required("student")
def api_mark_unique_id():
    payload = request.get_json(silent=True) or {}
    tag = normalize_unique_id(payload.get("unique_id", ""))
    subject = _normalize_subject(payload.get("subject", "General"))
    if not tag:
        return jsonify({"ok": False, "message": "Unique ID tag missing"}), 400

    db = get_db()
    student = db.execute("SELECT id, name FROM students WHERE unique_id = ? AND active = 1", (tag,)).fetchone()
    if not student:
        return jsonify({"ok": False, "message": "Unique ID tag not registered"}), 404

    if session.get("role") == "student" and student["id"] != _current_student_id():
        return jsonify({"ok": False, "message": "Students can mark only their own attendance"}), 403

    result = mark_attendance(student["id"], status="present", mode="unique_id", subject=subject)
    if result["newly_completed"]:
        message = f"All methods done. {student['name']} marked present for {result['subject']}"
    elif result["all_methods_completed"]:
        message = f"Attendance already completed for {result['subject']} today."
    else:
        pending = ", ".join(result["pending_methods"])
        message = f"Unique ID recorded. Pending: {pending}. Not present yet."
    return jsonify({"ok": True, "message": message, "student": {"id": student["id"], "name": student["name"]}, "result": result})


@attendance_bp.route("/api/mark/qr", methods=["POST"])
@login_required
@role_required("student")
def api_mark_qr():
    payload = request.get_json(silent=True) or {}
    raw_qr = payload.get("qr_data", "")
    db = get_db()
    token_candidate = _extract_qr_token_candidate(raw_qr)
    token_student_id, token_subject = _read_student_qr_token(token_candidate)

    student = None
    subject = _normalize_subject(payload.get("subject", "General"))

    if token_student_id:
        subject = token_subject
        student = db.execute(
            "SELECT id, name FROM students WHERE id = ? AND active = 1",
            (token_student_id,),
        ).fetchone()
    elif token_subject:
        subject = token_subject
        current_id = _current_student_id()
        if not current_id:
            return jsonify({"ok": False, "message": "Student account is not linked"}), 400
        student = db.execute(
            "SELECT id, name FROM students WHERE id = ? AND active = 1",
            (current_id,),
        ).fetchone()
    else:
        code, parsed_subject = _parse_qr_payload(raw_qr, subject)
        if not code:
            return jsonify({"ok": False, "message": "QR data missing"}), 400
        subject = parsed_subject
        student = db.execute(
            """
            SELECT id, name
            FROM students
            WHERE active = 1 AND (student_code = ? OR unique_id = ?)
            """,
            (code, code),
        ).fetchone()

    if not student:
        return jsonify({"ok": False, "message": "Student not found for scanned QR"}), 404

    if session.get("role") == "student" and student["id"] != _current_student_id():
        return jsonify({"ok": False, "message": "Students can mark only their own attendance"}), 403

    subject = _resolve_active_subject_for_mark(student["id"], subject, "qr")
    result = mark_attendance(student["id"], status="present", mode="qr", subject=subject)
    if result["newly_completed"]:
        message = f"All methods done. {student['name']} marked present for {result['subject']}"
    elif result["all_methods_completed"]:
        message = f"Attendance already completed for {result['subject']} today."
    else:
        pending = ", ".join(result["pending_methods"])
        message = f"QR recorded. Pending: {pending}. Not present yet."
    return jsonify(
        {
            "ok": True,
            "message": message,
            "student": {"id": student["id"], "name": student["name"]},
            "result": result,
            "subject": result["subject"],
        }
    )


@attendance_bp.route("/api/mark/face", methods=["POST"])
@login_required
@role_required("student")
def api_mark_face():
    if not is_face_available():
        return jsonify({"ok": False, "message": "AI module not installed"}), 400

    payload = request.get_json(silent=True) or {}
    image_data = payload.get("image")
    subject = _normalize_subject(payload.get("subject", "General"))
    if not image_data:
        return jsonify({"ok": False, "message": "Image missing"}), 400

    captured = extract_face_encoding(decode_data_url(image_data))
    if not captured:
        return jsonify({"ok": False, "message": "No clear face detected"}), 400

    db = get_db()
    students = db.execute(
        "SELECT id, name, photo_encoding FROM students WHERE active = 1 AND photo_encoding IS NOT NULL"
    ).fetchall()

    known = []
    index_to_student = []
    for s in students:
        encoding = from_json(s["photo_encoding"], default=[])
        if encoding:
            known.append(encoding)
            index_to_student.append(s)

    match_idx = match_face(captured, known)
    if match_idx is None:
        return jsonify({"ok": False, "message": "Face not recognized"}), 404

    student = index_to_student[match_idx]
    if session.get("role") == "student" and student["id"] != _current_student_id():
        return jsonify({"ok": False, "message": "Students can mark only their own attendance"}), 403
    result = mark_attendance(student["id"], status="present", mode="face", subject=subject)
    if result["newly_completed"]:
        message = f"All methods done. {student['name']} marked present for {result['subject']}"
    elif result["all_methods_completed"]:
        message = f"Attendance already completed for {result['subject']} today."
    else:
        pending = ", ".join(result["pending_methods"])
        message = f"Face recorded. Pending: {pending}. Not present yet."
    return jsonify({"ok": True, "message": message, "student": {"id": student["id"], "name": student["name"]}, "result": result})


def mark_attendance(student_id, status="present", mode="manual", note="", subject="General", manual_override=False):
    db = get_db()
    now_dt = datetime.now()
    today = date_iso()
    ts = now_iso()
    weekday = now_dt.weekday()
    current_hhmm = now_dt.strftime("%H:%M")
    recent_cutoff_ts = (now_dt - timedelta(minutes=20)).strftime("%Y-%m-%d %H:%M:%S")
    subject = _normalize_subject(subject)
    subject = _resolve_active_subject_for_mark(student_id, subject, mode)
    period_for_match = _get_period_for_student_subject(student_id, subject, weekday=weekday, current_hhmm=current_hhmm)
    if period_for_match:
        existing = db.execute(
            """
            SELECT id, status, mode, note, unique_id_done, face_done, qr_done
            FROM attendance
            WHERE student_id = ? AND date = ? AND subject = ?
              AND substr(timestamp, 12, 5) >= ?
              AND substr(timestamp, 12, 5) <= ?
            ORDER BY id DESC
            LIMIT 1
            """,
            (student_id, today, subject, period_for_match["start_time"], period_for_match["end_time"]),
        ).fetchone()
        # If no row is found in the active period window, fall back to today's
        # subject row so previously completed methods are not lost.
        if not existing:
            existing = db.execute(
                """
                SELECT id, status, mode, note, unique_id_done, face_done, qr_done
                FROM attendance
                WHERE student_id = ? AND date = ? AND subject = ?
                ORDER BY id DESC
                LIMIT 1
                """,
                (student_id, today, subject),
            ).fetchone()
    else:
        existing = db.execute(
            """
            SELECT id, status, mode, note, unique_id_done, face_done, qr_done
            FROM attendance
            WHERE student_id = ? AND date = ? AND subject = ?
            ORDER BY id DESC
            LIMIT 1
            """,
            (student_id, today, subject),
        ).fetchone()

    flags = {
        "unique_id": int(existing["unique_id_done"]) if existing else 0,
        "face": int(existing["face_done"]) if existing else 0,
        "qr": int(existing["qr_done"]) if existing else 0,
    }

    # Manual/auto-absent placeholder rows should not carry prior
    # biometric/QR completions into a new live marking attempt.
    if existing:
        is_manual_baseline = existing["mode"] == "manual" and existing["status"] in ("absent", "late")
        is_auto_absent_note = str(existing["note"] or "").startswith("Auto absent")
        if is_manual_baseline or is_auto_absent_note:
            flags = {"unique_id": 0, "face": 0, "qr": 0}

    previous_flags = dict(flags)
    if mode in REQUIRED_METHODS:
        flags[mode] = 1

    prev_all_done = all(previous_flags[m] == 1 for m in REQUIRED_METHODS)
    all_done = all(flags[m] == 1 for m in REQUIRED_METHODS)
    newly_completed = all_done and not prev_all_done
    pending_methods = [m for m in REQUIRED_METHODS if flags[m] != 1]
    period = _get_period_for_student_subject(student_id, subject, weekday=weekday, current_hhmm=current_hhmm)
    period_closed = bool(period and current_hhmm > period["end_time"])

    if mode == "manual":
        if manual_override:
            if status in ("absent", "late"):
                flags = {"unique_id": 0, "face": 0, "qr": 0}
                all_done = False
                pending_methods = list(REQUIRED_METHODS)
            final_status = status
        else:
            final_status = "present" if all_done else "absent"
    else:
        final_status = "present" if all_done else "absent"

    if period_closed and not manual_override and not all_done:
        note = (note + " | " if note else "") + f"Period closed at {period['end_time']}; pending required methods"

    if existing:
        db.execute(
            """
            UPDATE attendance
            SET status = ?, mode = ?, unique_id_done = ?, face_done = ?, qr_done = ?, timestamp = ?, synced = 0, note = ?, subject = ?
            WHERE id = ?
            """,
            (final_status, mode, flags["unique_id"], flags["face"], flags["qr"], ts, note, subject, existing["id"]),
        )
        attendance_id = existing["id"]
        operation = "update"
    else:
        try:
            cursor = db.execute(
                """
                INSERT INTO attendance (student_id, date, subject, status, mode, unique_id_done, face_done, qr_done, timestamp, synced, note)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?)
                """,
                (student_id, today, subject, final_status, mode, flags["unique_id"], flags["face"], flags["qr"], ts, note),
            )
            attendance_id = cursor.lastrowid
            operation = "insert"
        except sqlite3.IntegrityError:
            # Another request created the row first (same student/date/subject unique key); update it instead.
            winner = db.execute(
                """
                SELECT id, status, mode, note, unique_id_done, face_done, qr_done, timestamp
                FROM attendance
                WHERE student_id = ? AND date = ? AND subject = ?
                ORDER BY id DESC
                LIMIT 1
                """,
                (student_id, today, subject),
            ).fetchone()
            if not winner:
                raise

            # Merge winner flags only for near-time collisions, not stale rows.
            can_merge_winner = bool(
                winner["timestamp"]
                and not (winner["mode"] == "manual" and winner["status"] in ("absent", "late"))
                and not str(winner["note"] or "").startswith("Auto absent")
            )
            if can_merge_winner:
                flags["unique_id"] = max(int(winner["unique_id_done"] or 0), flags["unique_id"])
                flags["face"] = max(int(winner["face_done"] or 0), flags["face"])
                flags["qr"] = max(int(winner["qr_done"] or 0), flags["qr"])
                all_done = all(flags[m] == 1 for m in REQUIRED_METHODS)
                pending_methods = [m for m in REQUIRED_METHODS if flags[m] != 1]
                final_status = "present" if all_done else "absent"

            db.execute(
                """
                UPDATE attendance
                SET status = ?, mode = ?, unique_id_done = ?, face_done = ?, qr_done = ?, timestamp = ?, synced = 0, note = ?, subject = ?
                WHERE id = ?
                """,
                (final_status, mode, flags["unique_id"], flags["face"], flags["qr"], ts, note, subject, winner["id"]),
            )
            attendance_id = winner["id"]
            operation = "update"

    payload = {
        "attendance_id": attendance_id,
        "student_id": student_id,
        "date": today,
        "subject": subject,
        "status": final_status,
        "mode": mode,
        "unique_id_done": flags["unique_id"],
        "face_done": flags["face"],
        "qr_done": flags["qr"],
        "previous_unique_id_done": previous_flags["unique_id"],
        "previous_face_done": previous_flags["face"],
        "previous_qr_done": previous_flags["qr"],
        "all_methods_completed": all_done,
        "newly_completed": newly_completed,
        "pending_methods": pending_methods,
        "timestamp": ts,
        "note": note,
    }
    db.execute(
        "INSERT INTO sync_queue (entity_type, entity_id, operation, payload) VALUES (?, ?, ?, ?)",
        ("attendance", attendance_id, operation, to_json(payload)),
    )
    db.commit()

    return {
        "attendance_id": attendance_id,
        "mode": mode,
        "subject": subject,
        "status": final_status,
        "unique_id_done": flags["unique_id"],
        "face_done": flags["face"],
        "qr_done": flags["qr"],
        "previous_unique_id_done": previous_flags["unique_id"],
        "previous_face_done": previous_flags["face"],
        "previous_qr_done": previous_flags["qr"],
        "all_methods_completed": all_done,
        "newly_completed": newly_completed,
        "pending_methods": pending_methods,
        "time": datetime.now().strftime("%H:%M:%S"),
    }

